[package]
name = "rust-router"
version = "1.0.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
hostname = "0.4.1"
pnet = "0.35.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
